version: '3.1'
services:
  database:
    image: 'mongo'
    container_name: 'my_mongo_container'
    environment: 
      - MONGO_INITDB_DATABASE=my_db
      - MONGO_INITDB_ROOT_USERNAME=demo
      - MONGO_INITDB_ROOT_PASSWORD=demo
    ports: 
      - '27017:27017'